### ISSUE TITLE
Error in rule molecule_coverage

### ISSUE THREAD

**Issue by azwadriqbal** [pdimens/harpy#160]
### Describe the bug

Hi Pavel,

After updating harpy it looks like it runs into an error during the `harpy align` module. Specifically, I get this error repeating over my samples:
```
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:53:23 2024]
Error in rule molecule_coverage:
    jobid: 77
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz | depth_windo
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
[Wed Nov  6 12:53:23 2024]
Finished job 45.
28 of 95 steps (29%) done
[Wed Nov  6 12:54:36 2024]
Finished job 59.
29 of 95 steps (31%) done
[Wed Nov  6 12:54:47 2024]
Finished job 60.
30 of 95 steps (32%) done
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
```
I'm guessing this is an error arising from calculating molecule coverage.

I've uploaded my snakemake log here as well.

Thanks!
Azwad

### Is this the latest version of Harpy?

- [X] yes

### File that triggers the error (if applicable)

[align_strobe.1.06_11_2024.log](https://github.com/user-attachments/files/17651858/align_strobe.1.06_11_2024.log)

### Harpy error log

```console
(harpy) [ari22@cbsunt246 2302-flyF1s-pilot]$ harpy align strobe --conda -t 24 --contigs 2L,2R,3L,3R,4,X,Y -g ref/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa source_reads_fixed/*

BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:53:23 2024]
Error in rule molecule_coverage:
    jobid: 77
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz | depth_windo
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
[Wed Nov  6 12:53:23 2024]
Finished job 45.
28 of 95 steps (29%) done
[Wed Nov  6 12:54:36 2024]
Finished job 59.
29 of 95 steps (31%) done
[Wed Nov  6 12:54:47 2024]
Finished job 60.
30 of 95 steps (32%) done
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:56:09 2024]
Error in rule molecule_coverage:
    jobid: 69
    input: Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz | depth_windows
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 13:02:58 2024]
Error in rule molecule_coverage:
    jobid: 85
    input: Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz | depth_windo
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
(harpy) [ari22@cbsunt246 2302-flyF1s-pilot]$ \
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:53:23 2024]
Error in rule molecule_coverage:
    jobid: 77
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz | depth_windo50000 | gzip >
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
[Wed Nov  6 12:53:23 2024]
Finished job 45.
28 of 95 steps (29%) done
[Wed Nov  6 12:54:36 2024]
Finished job 59.
29 of 95 steps (31%) done
[Wed Nov  6 12:54:47 2024]
Finished job 60.
30 of 95 steps (32%) done
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:56:09 2024]
Error in rule molecule_coverage:
    jobid: 69
    input: Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz | depth_windows000 | gzip >
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 13:02:58 2024]
Error in rule molecule_coverage:
    jobid: 85
    input: Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz | depth_windo50000 | gzip >
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
(harpy) [ari22@cbsunt246 2302-flyF1s-pilot]$ \
    jobid: 77
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz | depth_windo50000 | gzip >
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
[Wed Nov  6 12:53:23 2024]
Finished job 45.
28 of 95 steps (29%) done
[Wed Nov  6 12:54:36 2024]
Finished job 59.
29 of 95 steps (31%) done
[Wed Nov  6 12:54:47 2024]
Finished job 60.
30 of 95 steps (32%) done
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:56:09 2024]
Error in rule molecule_coverage:
    jobid: 69
    input: Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz | depth_windows000 | gzip >
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 13:02:58 2024]
Error in rule molecule_coverage:
    jobid: 85
    input: Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz | depth_windo50000 | gzip >
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
(harpy) [ari22@cbsunt246 2302-flyF1s-pilot]$ \
    jobid: 77
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz | depth_win  dows.py 50000 | gzip >
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
[Wed Nov  6 12:53:23 2024]
Finished job 45.
28 of 95 steps (29%) done
[Wed Nov  6 12:54:36 2024]
Finished job 59.
29 of 95 steps (31%) done
[Wed Nov  6 12:54:47 2024]
Finished job 60.
30 of 95 steps (32%) done
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 12:56:09 2024]
Error in rule molecule_coverage:
    jobid: 69
    input: Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/ZS10-221220-3.bxstats.gz | depth_windo  ws.py 50000 | gzip >
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/ZS10-221220-3.molcov.gz
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/depth_windows.py", line 26, in <module>
    print(f"{LAST_CONTIG}\t{POSITION}\t{_SUM / WINSIZE}", file = sys.stdout)
                                        ~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 90, in <module>
    write_coverage(coverage, LASTCONTIG)
  File "/lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/molecule_coverage.py", line 52, in write_coverage
    sys.stdout.write(f"{contigname}\t{position}\t{freq}\n")
BrokenPipeError: [Errno 32] Broken pipe
[Wed Nov  6 13:02:58 2024]
Error in rule molecule_coverage:
    jobid: 85
    input: Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz, Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai
    output: Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
    shell:
        molecule_coverage.py -f Genome/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.fai Align/strobealign/reports/data/bxstats/3B-5-221221-15x.bxstats.gz | depth_win  dows.py 50000 | gzip >
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job molecule_coverage since they might be corrupted:
Align/strobealign/reports/data/coverage/3B-5-221221-15x.molcov.gz
```

**Comment by pdimens** [comment]
@azwadriqbal I have a fix issued for it, but the tests don't seem to run into the issue you've encountered. The quickest way to see if this works is for you to replace the `depth_windows.py` in your existing harpy installation with the code below.
You can easily find that script by being in the harpy conda environment and doing:
```bash
which depth_windows.py
```


The [hopefully] fixed script
```python
#! /usr/bin/env python

import sys
import argparse

parser = argparse.ArgumentParser(
    prog = 'depth_windows.py',
    description = 'Reads the output of samtools depth -a from stdin and calculates a windowed mean.'
    )
parser.add_argument('windowsize', type= int, help = "The window size to use to calcualte mean depth over (non-overlapping)")

args = parser.parse_args()
_SUM = 0
START = 1
END = args.windowsize
LAST_CONTIG = None
POSITION = 0

for line in sys.stdin:
    # Remove the newline character at the END of the line
    line = line.rstrip().split()
    contig = line[0]
    # the contig has changed, make the END POSITION the last POSITION, print output
    if LAST_CONTIG and contig != LAST_CONTIG:
        WINSIZE = (POSITION + 1) - START
        if WINSIZE > 0:
            depth = _SUM / WINSIZE
            print(f"{LAST_CONTIG}\t{POSITION}\t{depth}", file = sys.stdout)
        # reset the window START/END and sum
        _SUM = 0
        START = 1
        END = args.windowsize

    POSITION = int(line[1])
    _SUM += int(line[2])

    if POSITION == END:
        depth = _SUM / args.windowsize
        print(f"{contig}\t{END}\t{depth}", file = sys.stdout)
        # reset the window START/END and sum
        _SUM = 0
        START = END + 1
        END += args.windowsize
    LAST_CONTIG = contig
```

**Comment by azwadriqbal** [comment]
Hi Pavel,

Adjusting the above code seems to solve that particular error, but I'm running into this error when attempting to generate reports:
```
localrule sample_reports:
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Align/strobealign/reports/data/coverage/2B-1-221221-12x.cov.gz, Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    output: Align/strobealign/reports/2B-1-221221-12x.html
    log: Align/strobealign/logs/reports/2B-1-221221-12x.alignstats.log
    jobid: 86
    reason: Missing output files: Align/strobealign/reports/2B-1-221221-12x.html; Input files updated by another job: Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    wildcards: sample=2B-1-221221-12x
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/7c950d88d11158bb20ceb379f2611505_
RuleException:
CalledProcessError in file /local/workdir/azwad/2302-flyF1s-pilot/Align/strobealign/workflow/align_strobealign.smk, line 210:
Command 'source /lustre2/home/nt246_0001/ari22/miniforge3/envs/harpy/bin/activate '/local/workdir/azwad/2302-flyF1s-pilot/.snakemake/conda/7c950d88d11158bb20ceb379f2611505_'; set -euo pipefail;  Rscript --vanilla -e 'rmarkdown::render("/local/workdir/azwad/2302-flyF1s-pilot/.snakemake/scripts/tmpvia4zwu6.align_stats.Rmd", output_file="/local/workdir/azwad/2302-flyF1s-pilot/Align/strobealign/reports/2B-1-221221-12x.html", quiet=TRUE, knit_root_dir = "/local/workdir/azwad/2302-flyF1s-pilot", params = list(rmd="/local/workdir/azwad/2302-flyF1s-pilot/.snakemake/scripts/tmpvia4zwu6.align_stats.Rmd"))'' returned non-zero exit status 1.
[Wed Nov  6 17:26:07 2024]
Error in rule sample_reports:
    jobid: 86
    input: Align/strobealign/reports/data/bxstats/2B-1-221221-12x.bxstats.gz, Align/strobealign/reports/data/coverage/2B-1-221221-12x.cov.gz, Align/strobealign/reports/data/coverage/2B-1-221221-12x.molcov.gz
    output: Align/strobealign/reports/2B-1-221221-12x.html
    log: Align/strobealign/logs/reports/2B-1-221221-12x.alignstats.log (check log file(s) for error details)
    conda-env: /local/workdir/azwad/2302-flyF1s-pilot/.snakemake/conda/7c950d88d11158bb20ceb379f2611505_
Logfile Align/strobealign/logs/reports/2B-1-221221-12x.alignstats.log:
================================================================================
Error in `if (plot_contigs == "default") ...`:
! the condition has length > 1
Backtrace:
  1. rmarkdown::render(...)
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  6. knitr:::process_group(group)
  7. knitr:::call_block(x)
     ...
 14. base::withRestarts(...)
 15. base (local) withRestartList(expr, restarts)
 16. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 17. base (local) docall(restart$handler, restartArgs)
 19. evaluate (local) fun(base::quote(`<smplErrr>`))

Quitting from lines 627-646 [limit_contigs] (tmpvia4zwu6.align_stats.Rmd)
Execution halted
================================================================================
```

**Comment by azwadriqbal** [comment]
That's totally fine, thanks for addressing this!

**Comment by azwadriqbal** [comment]
@pdimens it looks like the issue still persists after installing the dev version. Based on the commit history on the main branch it doesn't look like there's been an update since I posted about the `--contigs` issue - should I have installed from a different branch? 

Thanks again for your help!

**Comment by pdimens** [comment]
Sorry about that, the fix was on a different branch, which has been merged into `main` now, so you can try again.

**Comment by azwadriqbal** [comment]
That fixed it, thanks!
